### PR TITLE
some minor grammar improvements for the website homepage

### PR DESCRIPTION
**Pull request by erikdw**
Modified `site_config/home.js` and then built `en-us/index.html` by running `docsite build` as per the README.

Notably, I received a failure when building the docsite:

```
✗ docsite build

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (...PATH_ELIDED.../openkruise/website/node_modules/natives/index.js:143:24)
    at Object.req [as require] (...PATH_ELIDED.../openkruise/website/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (...PATH_ELIDED.../openkruise/website/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Object.require.extensions.<computed> [as .js] (...PATH_ELIDED.../openkruise/website/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
```

### CODE REVIEW

**Comment by erikdw** [comment]
@FillZpp : why did you close this????

**Comment by veophi** [comment]
> @FillZpp : why did you close this????

openkruise website has been migrated to  [this repository](https://github.com/openkruise/openkruise.io)

**Comment by FillZpp** [comment]
> @FillZpp : why did you close this? This incorrect language still persists in the repo.

Yes, we have refactored this website with [docusaurus](https://docusaurus.io/), please see the latest master branch.

> openkruise website has been migrated to this repository

No, it hasn't... the tmp repo will be removed soon.

**Comment by erikdw** [comment]
Thanks for the response @veophi !

**Pull request closed without merging**
